name: Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  health_check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: all env
        run: echo "${{ github.event.head_commit.message }}"
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print env all again
        run: env
