name: Site Health Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Site Health
        uses: Jtalk/url-health-check-action@v3
        with:
          url: "https://grasshopperlabs.io"
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true
          expect-status: 200